angular.module('common', [

    'common.commonCtrl',
    'login',
    'dashboard',
    'session',
    'navigation',
    'profile',
    'admin',
    'grid',
    'carbonAppDirectives',
    'ngStorage',
    'carbonConfig',
    'toastr',
    'angular-loading-bar',
    'ngCookies',
    'form',
    'button',
    'ngImgCrop',
    'blueimp.fileupload',
    'datatables',
    'ngMessages',
    'treeControl',
    'ui-rangeSlider',
    'fiestah.money',
    'ui.bootstrap.typeahead',
    'ui.bootstrap.tabs',

    'cryoblock.common.templates'
]);
